# Publish releases to PyPI

name: Publish to PyPI

on:
  push:
    tags:
      - v*

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
  
    - name: Install dependencies
      run: python -m pip install --upgrade pip build flake8 mypy pytest
      
    - name: Check code style
      run: python -m flake8 .
      
    - name: Check typing
      run: python -m mypy .

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
      
    - name: Install the built package
      run: python -m pip install dist/*.whl
      
    - name: Run tests on the package
      run: pytest
        
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
